### ISSUE TITLE
`ResetPrompt` and `StepButtons` ?

### ISSUE THREAD

**Issue by dcsan** [jeanverster/chakra-ui-steps#35]
in the demo, where do you get the navigation buttons from?

`ResetPrompt` and `StepButtons` ?

I was going to add basic buttons but it seems they have specific methods required...

```
      {activeStep === 3 ? (
        <ResetPrompt onReset={reset} />
      ) : (
        <StepButtons
          nextStep={nextStep}
          prevStep={prevStep}
          prevDisabled={activeStep === 0}
        />
      )}
```

**Comment by dcsan** [comment]
btw thanks for the component, it's neat!

oh i found them in the storybook example

https://github.com/jeanverster/chakra-ui-steps/blob/a07eff0f8e021c925fbf6aefa2aca0a4ac6e9971/stories/Steps.stories.tsx

and now i see someone else had the same question
https://github.com/jeanverster/chakra-ui-steps/issues/1

you might want to make that clearer? without those buttons the component isn't functional

**Comment by jeanverster** [comment]
Hey @dcsan - yeah this has come up a couple times, I think the reason why I opted to make those into their own components was purely for brevity in the examples, but I get that it's confusing. The idea is that the user is responsible for calling the `nextStep` and `prevStep` methods from the `useSteps` hook themselves to allow for more flexibility.. I think I will update the examples so that they don't have these components and rather just regular chakra components to make it less confusing 👍🏼

**Comment by jeanverster** [comment]
I have updated the examples on the demo site to use only chakra components
